In [1]:
import pandas as pd
import numpy as np
import sklearn as sk

In [2]:
import os

df = pd.read_csv('../data/s1.csv')


In [3]:
import sys
sys.path.append('../src')

In [4]:
from event_simulator.builder import build_model, train_model, DataFeeder
from event_simulator.ptb_model import SmallConfig

config = SmallConfig()
raw_data = pd.read_csv('../data/s1.csv')

## test
data_feeder = DataFeeder(config)
data_feeder.pack_data(raw_data[['user_id', 'event']].values)


In [5]:
data_feeder.data.shape

(20, 1375)

In [6]:
data_feeder.data

array([[1, 3, 4, ..., 0, 0, 0],
       [1, 3, 4, ..., 0, 0, 0],
       [1, 3, 4, ..., 0, 0, 0],
       ..., 
       [1, 3, 4, ..., 0, 0, 0],
       [1, 3, 4, ..., 0, 0, 0],
       [1, 3, 4, ..., 0, 0, 0]], dtype=uint8)

In [15]:
a = np.array(range(24)).reshape(6,4)
z = np.zeros([4])

a[np.array([True, False, True, False, False, False])] = z
a

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])